set_property PACKAGE_PIN M15 [get_ports {input[1]}]
set_property PACKAGE_PIN H17 [get_ports {input[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input[0]}]
set_property PACKAGE_PIN U14 [get_ports {output[1]}]
set_property PACKAGE_PIN U19 [get_ports {output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[0]}]
