# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.cache/wt [current_project]
set_property parent.project_path /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/sources_1/imports/lab2_sources/delay.vhd
  /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/sources_1/imports/lab2_sources/encoder.vhd
  /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/sources_1/imports/lab2_sources/lab2.vhd
  /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/sources_1/imports/lab2_sources/oled_init.vhd
  /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/sources_1/imports/lab2_sources/oled_print.vhd
  /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/sources_1/imports/lab2_sources/spi_control.vhd
  /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/sources_1/imports/lab2_sources/top_level_circuit.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/constrs_1/imports/lab2_sources/lab2_constraints.xdc
set_property used_in_implementation false [get_files /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab2/lab2_complete/lab2.srcs/constrs_1/imports/lab2_sources/lab2_constraints.xdc]


synth_design -top top_level_circuit -part xc7z020clg484-1


write_checkpoint -force -noxdef top_level_circuit.dcp

catch { report_utilization -file top_level_circuit_utilization_synth.rpt -pb top_level_circuit_utilization_synth.pb }
