# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab1/lab1_complete/lab1_complete.cache/wt [current_project]
set_property parent.project_path /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab1/lab1_complete/lab1_complete.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab1/lab1_complete/lab1.vhd
read_xdc /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab1/lab1_complete/lab1_complete.srcs/constrs_1/new/lab1_constraints.xdc
set_property used_in_implementation false [get_files /home/bkhusain/hdrive/bulat_documents/events_conferences/Slovakia_summer_school/lab1/lab1_complete/lab1_complete.srcs/constrs_1/new/lab1_constraints.xdc]

synth_design -top lab1 -part xc7z020clg484-1
write_checkpoint -noxdef lab1.dcp
catch { report_utilization -file lab1_utilization_synth.rpt -pb lab1_utilization_synth.pb }
